<div class="docupload-page-description">
<?php echo $this->getLayout()
            ->createBlock('Magento\Cms\Block\Block')
            ->setBlockId('docupload-page-description')
            ->toHtml(); ?>
</div>
<form class="form form-docupload" method="POST" enctype="multipart/form-data" action="<?php echo $this->getUrl('docupload/index/post'); ?>" data-hasrequired="<?php echo __('* Required Fields') ?>" data-mage-init='{"validation":{}}'>
    <input type="hidden" name="customer_type" id="customer_type" value="2"/>
    <fieldset class="fieldset">
        <legend class="legend"><span><?= __('Documents of company:')?></span></legend>
        <div class="field document1_file required">    
            <label class="label" for="document1_file"><span><?php echo __('CNPJ:') ?></span></label>
            <div class="control">
                <input type="hidden" name="document1_type" id="document1_type" value="<?= __('CNPJ') ?>"/>
                <input name="document1_file" id="document1_file" value="" class="input-text" type="file" data-validate="{required-file:true}"/>
            </div>
        </div>
        <div class="field document2_file required">
            <label class="label" for="document2_file"><span><?php echo __('Contrato Social Consolidado:') ?></span></label>
            <div class="control">
                <input type="hidden" name="document2_type" id="document2_type" value="<?= __('Contrato Social Consolidado') ?>"/>
                <input name="document2_file" id="document2_file" value="" class="input-text" type="file" data-validate="{required-file:true}"/>
            </div>
        </div>
    </fieldset>
    <fieldset class="fieldset">
        <legend class="legend"><span><?= __('Documents of the partners in the company:')?></span></legend>
        <div class="field document3_file required">
            <label class="label" for="document3_file"><span><?php echo __('RG Partner %1%2', 'Administrador', ':') ?></span></label>
            <div class="control">
                <input type="hidden" name="document3_type" id="document3_type" value="<?= __('RG Partner %1%2', 'Administrador', '') ?>"/>
                <input name="document3_file" id="document3_file" value="" class="input-text" type="file" data-validate="{required-file:true}"/>
            </div>
        </div>
        <div class="field document4_file required">
            <label class="label" for="document4_file"><span><?php echo __('CPF Partner %1%2', 'Administrador', ':') ?></span></label>
            <div class="control">
                <input type="hidden" name="document4_type" id="document4_type" value="<?= __('CPF Partner %1%2', 'Administrador', '') ?>"/>
                <input name="document4_file" id="document4_file" value="" class="input-text" type="file" data-validate="{required-file:true}"/>
            </div>
        </div>
               
        <div class="field">
            <div class="control">
                <input type="checkbox" class="checkbox-partners" id="partners-check" name="partners-check" value=""> <?= __('Check if you have more partners in the company')?>
            </div>
        </div>
        <div class="partners-fields" style="display:none">
        <div class="field document5_file required">
            <label class="label" for="document5_file"><span><?php echo __('RG Partner %1%2', 2, ':') ?></span></label>
            <div class="control">
                <input type="hidden" name="document5_type" id="document5_type" value="<?= __('RG Partner %1%2', 2, '') ?>"/>
                <input name="document5_file" id="document5_file" value="" class="input-text" type="file" data-validate="{required-file:true}"/>
            </div>
        </div>
        <div class="field document6_file required">
            <label class="label" for="document6_file"><span><?php echo __('CPF Partner %1%2', 2, ':') ?></span></label>
            <div class="control">
                <input type="hidden" name="document6_type" id="document6_type" value="<?= __('CPF Partner %1%2', 2, '') ?>"/>
                <input name="document6_file" id="document6_file" value="" class="input-text" type="file" data-validate="{required-file:true}"/>
            </div>
        </div>
        </div>
        <?php echo $block->getChildHtml('form.additional.info'); ?>
    </fieldset>
    <div class="actions-toolbar">
        <div class="primary">
            <button type="submit" title="<?php echo __('Send Files') ?>" class="action submit primary">
                <span><?php echo __('Send Files') ?></span>
            </button>
        </div>
    </div>
</form>
<script type="text/javascript">
require([
    'jquery',
    'docupload',
    'docuploadPj',
    'domReady!'
], function($){
});
</script>